### ISSUE TITLE
error on npm start

### ISSUE THREAD

**Issue by crerem** [ahmadawais/create-guten-block#117]
I started today a new plugin and when i  "npm start" i get this errors

  
SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\residence\wp-content\plugins\playground\node_modules\cgb-scripts\config\webpack.config.dev.js:24:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! playground-cgb-guten-block@1.0.0 start: `cgb-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the playground-cgb-guten-block@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cretu\AppData\Roaming\npm-cache\_logs\2018-12-08T10_42_37_633Z-debug.log

My older plugin - works just fine on npm start. I did a version update on create-gutenberg-block before this so i don;t know if is a issue with a new version or something on my system.

Any ideea ?
Thank you

**Comment by ahmadawais** [comment]
File a bug report and answer the questions in it.
