### ISSUE TITLE
Cannot find module when installing

### ISSUE THREAD

**Issue by julpec** [ahmadawais/create-guten-block#207]
Hello

I try to install with `npx create-guten-block my-block` and I get this error :

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'which'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:10:25)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

1. `node -v`:
v10.16.0
2. `npm -v`:
6.9.0
3. `yarn --version` (if you use Yarn):
nop
4. `npm ls cgb-scripts` (if you haven’t ejected):

Operating system:
Debian 9.9

Thanks

**Comment by ahmadawais** [comment]
You didn't answer `npm ls cgb-scripts`

**Comment by julpec** [comment]
Sorry
This command return `empty`
I think it's quite normal because I did not install anything in my plugin directory. The first command with npx doesn't work, so nothing was done, correct ?
Sorry, I don't know much about npm and npx…
