### ISSUE TITLE
Problem with step #1 creating block

### ISSUE THREAD

**Issue by lcerliani** [ahmadawais/create-guten-block#239]
Hi everyone,
I'm having problems to creating de plugin in my plugins folder when I run `npx create-guten-block my-block`. When the process ends, in 'my-block' folder I have a 'node_modules' folder and a file named 'package.json'.

I show you the output:

```
📦   Creating a WP Gutenberg Block plugin called:  my-block 
 
 In the directory: /var/www/html/wp-content/plugins/my-block
 This might take a couple of minutes.

✔ 1. Creating the plugin directory called →  my-block 
⠸ 2. Installing npm packages.../root/.npm/_npx/3565/lib/node_modules/create-guten-block/index.js:60
	throw err;
	^

Error: Command failed: npm install cgb-scripts --save --save-exact --silent
Unable to save binary /var/www/html/wp-content/plugins/my-block/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/var/www/html/wp-content/plugins/my-block/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/var/www/html/wp-content/plugins/my-block/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/var/www/html/wp-content/plugins/my-block/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/var/www/html/wp-content/plugins/my-block/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/var/www/html/wp-content/plugins/my-block/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/var/www/html/wp-content/plugins/my-block/node_modules/node-sass/vendor' }
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/var/www/html/wp-content/plugins/my-block/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.16.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.13
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 8.16.1
gyp verb command install [ '8.16.1' ]
gyp verb install input version string "8.16.1"
gyp verb install installing version: 8.16.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.16.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/wp-content/plugins/my-block/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '8.16.1' ]
gyp verb install input version string "8.16.1"
gyp verb install installing version: 8.16.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.16.1
gyp verb ensuring nodedir is created /var/www/html/wp-content/plugins/my-block/node_modules/node-sass/.node-gyp/8.16.1
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.16.1' ]
gyp verb remove using node-gyp dir: /var/www/html/wp-content/plugins/my-block/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 8.16.1
gyp verb remove removing development files for version: 8.16.1
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.16.1' ]
gyp verb remove using node-gyp dir: /var/www/html/wp-content/plugins/my-block/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 8.16.1
gyp verb remove removing development files for version: 8.16.1
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/www/html/wp-content/plugins/my-block/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.9.0-11-amd64
gyp ERR! command "/usr/bin/node" "/var/www/html/wp-content/plugins/my-block/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/html/wp-content/plugins/my-block/node_modules/node-sass
gyp ERR! node -v v8.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

Building: /usr/bin/node /var/www/html/wp-content/plugins/my-block/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=

    at makeError (/root/.npm/_npx/3565/lib/node_modules/create-guten-block/node_modules/execa/index.js:169:9)
    at Promise.all.then.arr (/root/.npm/_npx/3565/lib/node_modules/create-guten-block/node_modules/execa/index.js:274:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```
Any tip would be welcome,
Thank you!
Lucas.

**Comment by ahmadawais** [comment]
It's a permission issue. Delete old folder and do it again. Or install npm in a way that it has no permission issues. Script is unable to create directories needed.
